import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import axios from "axios";

const inter = Inter({ subsets: ["latin"] });

axios.defaults.baseURL = "http://localhost:8000/";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        className={`${inter.className} grid h-screen font-serif text-white bg-gray-900 place-items-center`}
      >
        <div> {children}</div>
      </body>
    </html>
  );
}
